apiVersion: v1
kind: Service
metadata:
  name: product-api-service
spec:
  selector:
    app: product-api
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer
  externalIPs:
    - 192.168.1.6