apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
        - name: hurb-productapi
          image: cflip3/hurb-product-api:v1.2.6
          ports:
          - containerPort: 80
          resources: 
            limits:
              cpu: 300m
            requests: 
              cpu: 100m
              memory: 250Mi