apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
        - name: hurb-productapi
          image: cflip3/hurb-product-api:v1.2.6
          ports:
          - containerPort: 80
          resources: 
            limits:
              cpu: 50m
            requests: 
              cpu: 10m
              memory: 25Mi
            
---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: product-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product-api
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70