version: '3'
services:
    mysql:
        build: ./mysql
        image: cflip3/hurb-product-api-mysql:v1.0.7
        ports:
            - "3306:3306"
    app:
        build: ./app
        image: cflip3/hurb-product-api:v1.2.6
        depends_on:
            - mysql